title:              Purdue Winter Camp
email:              shseoul14@gmail.com
description:         CNU Global 4th Winter camp at Purdue Univ. 2019/12/30 - 2020/2/28 SeHyeong Lee , SuMin Lee
author:             Start Bootstrap
baseurl:            "/purdue-winter-camp-blog"
url:                "https://lsh23.github.io/purdue-winter-camp-blog/"

# Social Profiles
twitter_username:
github_username:    lsh23
facebook_username:  tpgud1995
linkedin_username:

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site
